### ISSUE TITLE
Domain is blocked by my university

### ISSUE THREAD

**Issue by sahilseth** [YuLab-SMU/clusterProfiler-book#2]
I have been trying to get this url un-blocked working with infosec, but they have found several domains ending with .top as malicious. 

Is there a quick way for me to access the book from github without being redirected to the other domain?

Thanks for the amazing tool!

**Comment by GuangchuangYu** [comment]
sorry to hear about this. Currently this is the only way we can view the book.

Maybe I will host the book in other mirror site.

**Comment by GuangchuangYu** [comment]
<https://htmlpreview.github.io/?https://github.com/YuLab-SMU/biomedical-knowledge-mining-book/blob/gh-pages/index.html>
