### ISSUE TITLE
重定向url

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/clusterProfiler-book#3]
鉴于这本书还是有不少人在访问，我们应该把<https://github.com/YuLab-SMU/clusterProfiler-book/tree/master/docs>目录下的`*.html`修改一下，让这些页面被访问到的时候，都重定向到新书相应的页面上<https://github.com/YuLab-SMU/biomedical-knowledge-mining-book/>

**Comment by huerqiang** [comment]
好的，老师，我明天整理一下。
